language: haxe

haxe:
  - development
  - "3.4.4"

dist: trusty
sudo: false

install:
  - haxelib install hxnodejs
  - haxelib install phantomjs
  - haxelib install utest
  - haxelib list
  - npm install

script:
  - haxe RunCi.hxml